# Generated by Django 5.1 on 2024-09-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productout_amountout_productout_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productout',
            name='amountOut',
        ),
    ]
